In [1]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [3]:
import numpy as np
import pprint as pp

t = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6])
pp.pprint(t)
print(t.ndim)  # rank
print(t.shape)
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])


array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6])
1
(6,)
0.1 0.2 0.6
[0.3 0.4 0.5] [0.5]
[0.1 0.2] [0.4 0.5 0.6]


In [6]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10.,11.,12.]])
pp.pprint(t)
print(t.ndim)
print(t.shape)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


In [11]:
t = tf.constant([1., 2., 3.])
tf.shape(t).numpy()

array([3], dtype=int32)

In [12]:
t = tf.constant([[1., 2.], [3.,4.]])
tf.shape(t).numpy()

array([2, 2], dtype=int32)

# Neural Network
 Perceptron => Backpropagation 
 $ f = Wx + b $, $ g = Wx $, $ f = g + b $
 1. $ \frac{\delta g}{\delta w} = x$, $ \frac{\delta g}{\delta x} = w $, $ \frac{\delta f}{\delta g} = 1 $, $\frac{\delta f}{\delta b} = 1 $
 2. $ \frac{\delta f}{\delta w} = \frac{\delta f}{\delta g} \cdot \frac{\delta g}{\delta w} = 1 * 5 = 5 $
 3. $ \frac{\delta f}{\delta x} = \frac{\delta f}{\delta g} \cdot \frac{\delta g}{\delta x} = 1 * -2 = -2 $ 
 * forward ( w = -2, x = 5, b = 3)
 * backward  
# Sigmoid
$$ g(z) = \frac{1}{1+e^{-z}} $$
z => *(-1) => exp => +(1) =>  inverse (1/x) => g